lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
markdown: kramdown
remove-theme: pages-themes/cayman
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
