lsi: false
safe: true
source: docs
incremental: false
highlighter: rouge
markdown: kramdown
remote-theme: cayman
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
