lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
markdown: kramdown
remote-theme: cotes2020/jekyll-theme-chirpy
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
