lsi: false
safe: true
incremental: false
highlighter: rouge
markdown: kramdown
remote-theme: pages-themes/xayman
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
